name: Deploy Site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Shared Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Check latest code
        uses: actions/checkout@v4
      - name: Setup Node Js
        uses: actions/setup-node@v4
      - name: Install Node Js Dependencies
        run: npm install
      - name: Build Production
        run: npm run build
      - name: Push build to Shared Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/build/
      - name: Connect to SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: "cd domains/kubahdutamadinna.com/duta-madinna-kubah && ./.scripts/deploy.sh"
